"""create_production_plans_table

Revision ID: 450977dccc60
Revises: f9025cd873c1
Create Date: 2026-06-29 23:36:50.259533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450977dccc60'
down_revision: Union[str, Sequence[str], None] = 'f9025cd873c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('animation_profile', sa.Enum('basic', 'standard', 'high', 'cinema', name='animationprofile', native_enum=False), nullable=False),
    sa.Column('production_profile', sa.Enum('shorts', 'reel', 'long_form', 'series', name='productionprofile', native_enum=False), nullable=False),
    sa.Column('quality_profile', sa.Enum('draft', 'standard', 'high', 'ultra', name='qualityprofile', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_plans_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plans_id'))

    op.drop_table('production_plans')
    # ### end Alembic commands ###
