"""add_project_configuration_fields

Revision ID: c82a0b2292de
Revises: 164be27a3631
Create Date: 2026-06-29 15:51:17.128102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82a0b2292de'
down_revision: Union[str, Sequence[str], None] = '164be27a3631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_type', sa.Enum('short', 'medium', 'long', 'series', name='videotype', native_enum=False), nullable=False, server_default='medium'))
        batch_op.add_column(sa.Column('target_duration_seconds', sa.Integer(), nullable=False, server_default='180'))
        batch_op.add_column(sa.Column('aspect_ratio', sa.Enum('9:16', '16:9', '1:1', name='aspectratio', native_enum=False), nullable=False, server_default='16:9'))
        batch_op.add_column(sa.Column('language', sa.String(length=100), nullable=False, server_default='English'))
        batch_op.add_column(sa.Column('art_style', sa.Enum('anime', 'manhwa', 'manga', 'semi_realistic', name='artstyle', native_enum=False), nullable=False, server_default='anime'))
        batch_op.add_column(sa.Column('narration_style', sa.Enum('third_person', 'first_person', name='narrationstyle', native_enum=False), nullable=False, server_default='third_person'))
        batch_op.add_column(sa.Column('subtitle_language', sa.String(length=100), nullable=False, server_default='English'))
        batch_op.add_column(sa.Column('voice_gender', sa.Enum('male', 'female', name='voicegender', native_enum=False), nullable=False, server_default='male'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('voice_gender')
        batch_op.drop_column('subtitle_language')
        batch_op.drop_column('narration_style')
        batch_op.drop_column('art_style')
        batch_op.drop_column('language')
        batch_op.drop_column('aspect_ratio')
        batch_op.drop_column('target_duration_seconds')
        batch_op.drop_column('video_type')

    # ### end Alembic commands ###
