"""add_error_message_to_generation_jobs

Revision ID: f9025cd873c1
Revises: 6fbecf8cb948
Create Date: 2026-06-29 22:23:37.284291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9025cd873c1'
down_revision: Union[str, Sequence[str], None] = '6fbecf8cb948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
